Make the upgrade catch an error in nixos-rebuild

diff --git a/hack/update b/hack/update
--- a/hack/update
+++ b/hack/update
@@ -5,6 +5,10 @@ set -euo pipefail
 nix flake update
 hostname="$(hostname -s)"
 sudo nixos-rebuild switch --flake .#"$hostname"
+if [ $? -ne 0 ]; then
+	echo "nixos-rebuild failed, aborting update"
+fi
+git checkout main
 git add flake.lock
 git commit -m "Update flake.lock"
-
+git push origin main
